spring:
  datasource:
    url: jdbc:mysql://bw-db:3306/book_wise
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
    swagger-ui:
      path: "/api-docs"

logging:
  level:
    root: warn